name = "StringManipulation"
uuid = "892a3eda-7b42-436c-8928-eab12a02cf0e"
authors = ["Ronan Arraes Jardim Chagas <ronan.arraes@inpe.br>"]
version = "0.3.0"

[compat]
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[targets]
test = ["Test", "Markdown"]
